### ISSUE TITLE
HGI80 incorrectly detected as an evofw3

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/evohome#104]
From [HA forum](https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/4217?u=zxdavb)

------------

Latest version, and I get this in the logs now:
```
/dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT5S4V48-if00-port0: the gateway type is not determinable, will assume evofw3, TIP: specify the serial port by-id (i.e. /dev/serial/by-id/usb-...)
```
As you can see, I’m already using /dev/serial/by-id…

It says treating as an evofw3 device, however, I actually have a serial HGI80 connected via USB adapter. It works fine but latest updates treat it as an **evofw3**.

Can we have a manual switch to tell it what it is?

**Comment by Onl1ne1373** [comment]
Interesting, my HGI80 does not have a FTDI chipset, but a TUSB3410: 
`/dev/serial/by-id/usb-Texas_Instruments_TUSB3410_Boot_Device_TUSB3410-if00-port0`

**Comment by zxdavb** [comment]
Actually, this is a **HGS80** attached via a Rs232-USB adapter. The 
`/dev/serial/by-id/usb-FTDI_USB-RS232_Cable_FT5S4V48-if00-port0` 
is the adapter, not the **HGS80**.

**Comment by zxdavb** [comment]
This has been addressed with a less unhelpful error message

**Comment by zxdavb** [comment]
```python
    _LOGGER.warning(
        f"{serial_port}: the gateway type is not determinable, will assume evofw3"
        + (
            ", TIP: specify the serial port by-id (i.e. /dev/serial/by-id/usb-...)"
            if "by-id" not in serial_port
            else ""
        )
    )
```
