### ISSUE TITLE
000E Payload doesn't match

### ISSUE THREAD

**Issue by Onl1ne1373** [zxdavb/evohome#106]
```
18:06:14.693  I --- 21:033394 --:------ 21:033394 000E 003 000028 < Payload doesn't match '^000014$': 000028
```

Got 2000 of these today. It is a Spider Thermostat.

**Comment by zxdavb** [comment]
Could you provide a packet log? Maybe we can decode the purpose & meaning of `000E`?

**Comment by Onl1ne1373** [comment]
I looked through my packet logs and I always have the payload 000028 for Spiders:

```log
2024-03-05T23:58:25.809671 059  I --- 21:033620 --:------ 21:033620 000E 003 000028
```

One other packet that I found was:
```log
2024-02-29T19:23:12.013200 094  I --- 34:209034 --:------ 34:209034 000E 003 000014
```
But this is not a device that I own.

**Comment by zxdavb** [comment]
I was hoping your system would flit between `14` and `28` - so that we could work out what the values represented by looking a contemporaneous packets.

**Comment by zxdavb** [comment]
This particular error message, "Payload doesn't match", will be fixed in an upcoming release.
