### ISSUE TITLE
So many Warning messages logged in HomeAssistant

### ISSUE THREAD

**Issue by trailro** [zxdavb/evohome#114]
Hi all,

Since upgrading to the latest version of ramses_rf and ramses_cc, my HomeAssistant logs are flooded with warnings that I can't seem to ignore for some reason. I get about 1k messages a day as per the below.

Logger: ramses_tx.protocol_fsm
Source: runner.py:190
First occurred: 27 May 2024 at 16:06:56 (1039 occurrences)
Last logged: 21:14:29

    TOUT.. = <ProtocolContext state=WantEcho cmd_=2349|RQ|01:256364|02, tx_count=1/4>: echo_timeout=0.5
    TOUT.. = <ProtocolContext state=WantEcho cmd_=2349|RQ|01:256364|0B, tx_count=1/4>: echo_timeout=0.5
    TOUT.. = <ProtocolContext state=WantEcho cmd_=2349|RQ|01:256364|00, tx_count=1/4>: echo_timeout=0.5
    TOUT.. = <ProtocolContext state=WantEcho cmd_=3220|RQ|10:056759|19, tx_count=1/4>: echo_timeout=0.5
    TOUT.. = <ProtocolContext state=WantEcho cmd_=3220|RQ|10:056759|00, tx_count=1/4>: echo_timeout=0.5

**Comment by zxdavb** [comment]
These warnings can be ignored. They are essentially logspam, and will be removed in future.
