### ISSUE TITLE
Possibly missing functionality for Intergas boilers

### ISSUE THREAD

**Issue by renede** [zxdavb/evohome#125]
Configuration:
Homeassistant 2024.7.4
HasOs 12.4
RPi4-64
RAMSES-ESP via USB on RPi
RAMSES RF 0.41.23

My Evohome system is successfully controlled with RAMSES RF
The Evohome system is controlling 4 zones, 2 of them with zone valves
and local thermostats, and 2 with HR80 radiator valves. The boiler is 
controlled in on/off mode through HC60NG and BDR91 relays.
My new Intergas Xtreme 36 boiler has weather dependent control.

The boiler can be RF connected to Honeywell thermostats, so I assume it
to follow the ramses 2 protocol. It was initially not detected by the
RAMSES RF integration. Only when I paired it with the Evohome controller,
the boiler became visible as an opentherm bridge (serial 10:170117), 
but most of its about 30 "diagnostic" entities were "Unavailable".
Only "CH active", "DHW active" and "Flame active" entities were available, 
always showing the 'Off' state, even when the boiler was clearly heating.

Pairing with the Evohome had the adverse effect of switching the boiler
to opentherm mode, disabling the weather dependent control. In order to 
restore that I had to remove the boiler from the Evohome controller and
to switch the boiler to ignore opentherm demand (set its parameter P057
to 0). After that, the boiler was still visible in RAMSES RF, with the
same false or "Unavailable" "Diagnostic" entities.

I have no knowledge of the protocols involved, but I assume that the boiler
must somehow be queried to provide its status data. Is this possible
with RAMSES RF?

**Comment by zxdavb** [comment]
To progress this, I'll need you to provide a contemporaneous packet log.

In addition, you should log this issue this on: https://github.com/zxdavb/ramses_cc (so I am closing it here)
