### ISSUE TITLE
Show Outside Temperature

### ISSUE THREAD

**Issue by megapearl** [zxdavb/evohome#13]
This is not an issue, but a feature request.

Is it possible to display the outside temperature in homeassistant via your component?
My evohome controller has a sensor outside which displays the outside temperature on the controller (in the upper left corner of the evotouch)
It would be great if you can implement it in the future.

Best Regards,
Donald.

**Comment by zxdavb** [comment]
I can certainly show a temperature.  In fact, I _will probably_ end up showing a temperature in the HA component (see issue #12). I am not happy about it, though...

>The honeywell api, as currently documented, does not expose this information.  Either for locations with a weather sensor (like yours), or for those who don't, but still get the 'outside' temperature displayed in the UI.

So, all I could do is poll another web api for that data.  I could even poll the same web api as does the EvoTouch.  Why should l though? HA does a good enough job of that already.

**Comment by megapearl** [comment]
So you can’t pull the outside temperature out of the controller, local and remote.
Hmmmz
