### ISSUE TITLE
Receiving warning in log despite logging level set to INFO

### ISSUE THREAD

**Issue by pensionado** [zxdavb/evohome#14]
Keep getting warning messages for current_temperature and target_temperature, despite logging level set to INFO. In researching the problem is this caused by statements 1082 and 1094 of evohome.py in the custom_components directory saying _LOGGER.warn instead of _LOGGER.warning ?
```
_LOGGER.warn("target_temperature(%s) = %s", self._id, avg_temp)
_LOGGER.warn("current_temperature(%s) = %s", self._id, avg_temp)

**Comment by zxdavb** [comment]
Yes.  This custom component is teh 'development' sibling to the 'official' HA component: https://www.home-assistant.io/components/climate.evohome/ (this link will come live in 0.80).

There is a lot of logging in this version (but not in the HA version, they won't have it).  

I switch `debug`s to `warning`s (or add `warning`s) whenever I tweak a part of the code, as the community using this component act as guinea pigs for that code. 

The intention is to have `DEBUG`s only.

I will remove these, at start back-porting seom stuff from the HA version when I finish refurbishing my front room (where the dev server normally sits).

**Comment by pensionado** [comment]
Thanks, much appreciated for your work on this.
