### ISSUE TITLE
All zones are showing the temperature as Unavailable?

### ISSUE THREAD

**Issue by DoneInSeconds** [zxdavb/evohome#15]
Hey, I found your component as I have the EU version, so I thought I'd give it a go. However, I'm unable to get it working. It's picked up all my zones, but it's not displaying any of the temperatures:

![climate](https://user-images.githubusercontent.com/22151993/46628676-3a34a000-cb36-11e8-8962-2917d4abe19f.png)

I have a tonne of errors like this in the event viewer:

> 
> Mon Oct 08 2018 20:06:20 GMT+0100 (British Summer Time)
> 
> > Error doing job: Task exception was never retrieved
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 241, in async_update_ha_state
> >     attr = self.state_attributes or {}
> >   File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 341, in state_attributes
> >     self.hass, self.target_temperature, self.temperature_unit,
> >   File "/config/custom_components/evohome.py", line 1079, in target_temperature
> >     for zone in self._status['zones']]
> >   File "/config/custom_components/evohome.py", line 1079, in <listcomp>
> >     for zone in self._status['zones']]
> > KeyError: 'setpointStatus'

![climateerrors](https://user-images.githubusercontent.com/22151993/46628682-3f91ea80-cb36-11e8-8359-7fa02e324c51.png)

Any help you can offer would be most appreciated! I'm using Hass.io (latest version [133]).

EDIT: Something else I just noticed is that the graph seems to work fine and displays the live temperature history, but it just doesn't show the temperature against the zones (on the dashboard or in the entities list).

**Comment by zxdavb** [comment]
You need to give me better log dumps.  Don't bother with UI screen captures, unless I specifically ask.

Try downloading the latest version (I just did a push), restart HA and try: `cat home-assistant.log | grep available\( | head -n 20` and `cat home-assistant.log | grep _status | head -n 20` - we can go from there...

Regarding the graphs - most of that data is historical, and it seems to plot a straight (horizontal) line from the last real data point, so don't be fooled.

To be clear, are you saying that they have never been 'available'?  They must have been available at some stage, according to your post...

**Comment by DoneInSeconds** [comment]
To be clear, they had never been available. I dropped the files into custom_components, added the config and restarted HA a few times waiting 10-15 minutes between restarts. They just showed unavailable as per my screenshot.

I've dropped your new file in and restarted; it's now working perfectly.

**Comment by zxdavb** [comment]
Ha! "To be clear" sounds a bit passive-aggressive when it's thrown back at me - sorry if I gave that impression. 😄 

All good then. I am curious, where you using the old Honeywell component?

And BTW, you've inadvertently pointed out a bug in my code!

**Comment by DoneInSeconds** [comment]
It did a bit, no worries :). I know how the rest of the company probably feel when I ask them for better repros! 

I tried the climate/-honeywell one but it just didn't work properly. I fetched your version down at 19:30ish tonight (GMT), which is when I got the issues. I then re-fetched it when you told me to and it worked fine!

**Comment by zxdavb** [comment]
All good then. Enjoy evohome.
