### ISSUE TITLE
Python 3.13 unsupported: module 'logging' has no attribute '_acquireLock'

### ISSUE THREAD

**Issue by bramkragten** [zxdavb/evohome#161]
Python 3.13, shipped with Home Assistant 2024.12 is not supported by `ramses_rf`.
`logging._acquireLock` is no longer present in Python 3.13.

```
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/logger.py", line 212, in getLogger
    logging._acquireLock()  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'
```

**Comment by zxdavb** [comment]
In the latest **master** branch, we have:
https://github.com/zxdavb/ramses_rf/blob/99d06ac5825203b6b3621f58750be77d358f5a01/src/ramses_tx/logger.py#L211-L215

This should solve the issue: I'll push an update ASAP.
