### ISSUE TITLE
Next steps in HA?

### ISSUE THREAD

**Issue by jriguera** [zxdavb/evohome#17]
Hi @zxdavb I would like to know when (more or less) are you planning to add the rest of the functionality to the official HA evohome component (introduced in HA v0.80)

Great work!
Jose

**Comment by jriguera** [comment]
Yep, I am aware of the architectural changes required in HA, as you are involved in the discussions with HA developers, do you have a rough estimate if `b` and `c` could be achieved at some time this year?

I guess for now it would be nice to have `a`. I am also renovating my house, looking forward to get it!

**Comment by zxdavb** [comment]
Do you not know about the custom component, which has all the features identifed above? https://github.com/zxdavb/evohome-client

**Comment by zxdavb** [comment]
And I am hoping to get the official component done in the coming months...

**Comment by jriguera** [comment]
I know about your custom component, but I would prefer using the one integrated in HA. I am assuming is not possible using both (official vs custom component) at the same time (I haven't tried) and, for now, it will be enough for me having the zones (point `a`).

Thanks!

**Comment by zxdavb** [comment]
You can run both at once, but you need to change the name of the custom component. Look at: https://github.com/zxdavb/evohome/issues/10

**Comment by zxdavb** [comment]
will close this for now:
> a) add heating zones (easy) with all operating modes (architectural change to HA)
zones added, but all operating modes wont happen until at least climate v2

> b) add DHW controller (architectural change to HA)
awaiting architectural change in HA

> c) add missing operating modes to controller (architectural change to HA)
awaiting architectural change in HA
