### ISSUE TITLE
Add support for custom_updater

### ISSUE THREAD

**Issue by quentinsf** [zxdavb/evohome#24]
Hi David - as suggested, here's a request for the JSON file that would allow this to be managed using the [custom_updater](
https://github.com/custom-components/custom_update).  The spec for the JSON file is [here](https://github.com/custom-components/custom_updater/wiki/components).  You'd need to add a VERSION to your .py files and have a JSON file (typically custom_components.json) that looked pretty much like this:

    {
        "evohome_cc": {
            "version": "0.1.2",
            "local_location": "custom_components/evohome_cc.py",
            "remote_location": "https://raw.githubusercontent.com/zxdavb/evohome/evohome_cc/evohome_cc.py",
            "visit_repo": "https://github.com/zxdavb/evohome/tree/evohome_cc",
            "changelog": "https://github.com/zxdavb/evohome/blob/evohome_cc/README.md"
        },
        "climate.evohome_cc": {
            "version": "0.1.2",
            "local_location": "custom_components/climate.evohome_cc.py",
            "remote_location": "https://raw.githubusercontent.com/zxdavb/evohome/evohome_cc/climate/evohome_cc.py",
            "visit_repo": "https://github.com/zxdavb/evohome/tree/evohome_cc",
            "changelog": "https://github.com/zxdavb/evohome/blob/evohome_cc/README.md"
        },
        "water_heater.evohome_cc": {
            "version": "0.1.2",
            "local_location": "custom_components/water_heater.evohome_cc.py",
            "remote_location": "https://raw.githubusercontent.com/zxdavb/evohome/evohome_cc/water_heater/evohome_cc.py",
            "visit_repo": "https://github.com/zxdavb/evohome/tree/evohome_cc",
            "changelog": "https://github.com/zxdavb/evohome/blob/evohome_cc/README.md"
        }
    }

and you just need to keep the versions in sync and perhaps provide a changelog.

Ta!

**Comment by zxdavb** [comment]
OK, have a play with this - still in beta, though...

**Comment by quentinsf** [comment]
Splendid! - but my demo had a typo, I'm afraid, and I led you astray. I think the `local_location` should have slashes where I have dots - it's a filesystem path not a python path.  

ie.
`"local_location": "custom_components/water_heater/evohome_cc.py",`
not
`"local_location": "custom_components/water_heater.evohome_cc.py",`

I made a temporary copy of your custom_components.json on another URL and it works nicely once I make that change:

![](https://www.cl.cam.ac.uk/~qs101/evohome_cc/custom_updater.png)

**Comment by zxdavb** [comment]
I didn't spot it - thanks for testing, would you like try again & let me know?

**Comment by zxdavb** [comment]
just done - can I see your `lovelace-ui.yaml`? I can't get it working my end, but I don't use lovelace normally...

**Comment by quentinsf** [comment]
Great - here's what my UI looks like now:

![](https://www.cl.cam.ac.uk/~qs101/evohome_cc/custom_updater2.png)

and here's the relevant bit from configuration.yaml:

```
custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
    - https://raw.githubusercontent.com/zxdavb/evohome/evohome_cc/custom_components.json
```

Re the changes to `ui-lovelace.yaml`, note the filename, and note that it's only used now [if you have lovelace in YAML mode](https://www.home-assistant.io/lovelace/yaml-mode/).  (If not, you can do this via the new GUI editor, I guess.)

First, you need to get the tracker-card component (a single javascript file) and put it in `/config/www` as described [here](https://github.com/custom-cards/tracker-card).

Then at the top of your `ui-lovelace.yaml` you need to include it as a custom resource:

```
resources:
  - url: /local/tracker-card.js?v=0
    type: js
```

and then add it as a card within your view definition, eg:

```
views:
  ...
  # I have a tab called 'Misc'
  - title: Misc
    path: misc_view
    badges: []
    cards:

      ...blah blah...

      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
```
Anyway, I clicked 'Update all' and nothing apparently happened, but when I then hit the check button shortly afterwards, I found the files had all updated to 0.9.2 as expected.

Thanks!

**Comment by zxdavb** [comment]
OK, gottit (can't spell loveloce).

**Comment by zxdavb** [comment]
Done.

**Comment by quentinsf** [comment]
Ah - glad to see you're dropping the evohome_cc branch - I guess I should use the URL

https://raw.githubusercontent.com/zxdavb/evohome/master/custom_components.json

in my config now.

**Comment by quentinsf** [comment]
You _might_ just want to leave 'master' in the individual URLs for the .py file, I'd suggest.  Fewer places to make changes.  At the moment, for example, the specified URL:

https://raw.githubusercontent.com/zxdavb/evohome/v0.9.4/water_heater/evohome_cc.py

actually points to a file which is version 0.9.2, so it looks as if the update hasn't worked...

The logic that feels as if it makes sense to me is:

* Check the version of your local copies against the version specified in the current JSON file in master.
* If they aren't the same, then download new versions from master.

But it depends how you use master.  I tend to use git-flow on my projects, so small changes happen in 'develop', and 'master' is always my current public release, so the above would make sense. 

If you update the python code in master in between 'official' releases, though, then using the tag URLs as you've done is the better approach... if they point to the right place :-)

All the best, 
Quentin

**Comment by zxdavb** [comment]
At the moment, for example, the specified URL:
> 
> https://raw.githubusercontent.com/zxdavb/evohome/v0.9.4/water_heater/evohome_cc.py
> 
> actually points to a file which is version 0.9.2, so it looks as if the update hasn't worked...

Woops!

**Comment by quentinsf** [comment]
Brilliant - updates nicely now - thanks!
