### ISSUE TITLE
Rename evohome controller to fix Home Assistant deprecation

### ISSUE THREAD

**Issue by WoLpH** [zxdavb/evohome#26]
It seems that Home Assistant is deprecating certain types of entity IDs so the following line has to change:

https://github.com/zxdavb/evohome/blob/f998615def6dee82ca4af171dc4fe553498bb760/climate/evohome_cc.py#L540

The Home Assistant code that checks for invalid names: https://github.com/home-assistant/home-assistant/blob/bada9b5e0b455fd712d0f8e749b5dc26edb4c4e1/homeassistant/helpers/config_validation.py#L153-L169

It appears that the underscore prefix is not allowed, but perhaps there are more issues. The related change in Home Assitant: https://github.com/home-assistant/home-assistant/pull/20478

**Comment by zxdavb** [comment]
I used the _prefix to get the TCS to the top of any ordered list of zones (since HA treats the TCS as a climate device rather than a 'hub').  For the same reason, the DHW controller is called `~DHW` (but to the bottom of the list).

For now, I have taken the underscore away from the TCS.

**Comment by zxdavb** [comment]
Changed to:
```python
self._name = obj_ref.location.name 
```

It seems ~DHW is OK (in the sense that it doesn't throw a warning in the log):
```python
self._name = "~DHW"
```

**Comment by zxdavb** [comment]
Will close for now, but I have asked devs for guidance about `~DHW`, and I will have to update the official component at some time.
