### ISSUE TITLE
Changing Temperature

### ISSUE THREAD

**Issue by Tacchi1983** [zxdavb/evohome#27]
I think there is a problem when changing the temperature while being on PermanentOverride . It changes the temp but it changes only for 2 hours(till next setpoint), while being on PermanentOverride in HA. For example. I changed the livingroom to 21 degrees at 10.30 in Ha in permanent override, but when i look in my evohome app it says it wil change only till 12.30, so its not in permanent override anymore. When changing from temporary override to permanent override in Ha it stays the same for 2 hours so it doesnt change to permanent override . U can change from follow the schedule to permanent override. Then the state is correct. Why is temperary override not till next setpoint from follow schedule and only for 2 hours. Can u check this pls. Thk u
Example in log : for permanent override mode temperature schould not be None (will use current target temp).

**Comment by zxdavb** [comment]
This is due to a limitation of HA; the long-term solution is to create a custom service call.

I will try to address this, but I do not have a lot of spare capacity at the moment.

**Comment by zxdavb** [comment]
@Tacchi1983 There were some bugs found/squashed that may have addressed this issue.

Can you confirm if it is still here with **HA** v0.88, and **evohome_cc** v0.9.9?

**Comment by zxdavb** [comment]
I believe this is fixed with the latest version of HA (on/before HA v0.100).
