### ISSUE TITLE
Component not loading

### ISSUE THREAD

**Issue by megapearl** [zxdavb/evohome#3]
Can't get the new component to work/load,

In /etc/homeassistant/configuration.yaml I have:

```
evohome:
    username: !secret evohome_username
    password: !secret evohome_password
```

I tried the following directories for evohome.py

```
/etc/homeassistant/custom_components/
/etc/homeassistant/custom_components/climate/
/etc/homeassistant/custom_components/evohome/

```
In log:
```
2018-06-10 14:34:49 ERROR (MainThread) [homeassistant.loader] Unable to find component evohome
2018-06-10 14:34:49 ERROR (MainThread) [homeassistant.setup] Setup failed for evohome: Component not found.

```
and
```
2018-06-10 14:40:35 ERROR (MainThread) [homeassistant.loader] Unable to find component climate.evohome
2018-06-10 14:40:35 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform climate.evohome: Platform not found.

```
Am I missing something?

**Comment by zxdavb** [comment]
Not sure.  If your configuration file is: `/etc/homeassistant/configuration.yaml`, then you should have these two files:
```
/etc/homeassistant/custom_components/evohome.py
/etc/homeassistant/custom_components/climate/evohome.py
```

**Comment by zxdavb** [comment]
Someone else has loaded the component, so I am confident the problem is not at my end (I've been wrong before), tho': https://community.home-assistant.io/t/honeywell-evohome-thermostat-work-started-need-advice/43740/30

**Comment by megapearl** [comment]
You're right.
I thought the /evohome.py was enough (just like the old climate component) but it is needing the /climate/evohome.py also...
Never mind, got it working now, without any error.

**Comment by zxdavb** [comment]
Woot! Closed.
