### ISSUE TITLE
Data sampling rate for DHW less than expected

### ISSUE THREAD

**Issue by jarrah31** [zxdavb/evohome#32]
Is the data sampling rate lower for water_heater compared to climate out of interest? I've noticed a definite reduction in the detail shown for my DHW graphs compared to how it used to be. The graphs below show the difference between the two. (unfortunately I have no evidence how it used to be because I deleted the DB table for DHW whilst troubleshooting the stuck temp issue)

![image](https://user-images.githubusercontent.com/3072303/53198883-7e23cf80-3615-11e9-9054-0f565123b0c9.png)

btw, happy to give you access to my DHW if it'll help with troubleshooting.

_Originally posted by @jarrah31 in https://github.com/zxdavb/evohome/issues/30#issuecomment-466150202_

**Comment by zxdavb** [comment]
@jarrah31 There _should_ be no difference in sampling for water heaters.

**Comment by zxdavb** [comment]
I am chasing this now, will let you know.

**Comment by jarrah31** [comment]
Much appreciated! I've been looking at database entries to see if there was any difference between what is sent to influxdb vs the internal HA one, along with creating creating graphs on HA and comparing them to Grafana. So far they look the same which is good as it rules out any external influences.

I'll install the latest 0.9.9 this evening on my v0.88.2 HA build and will let you know if I see any difference.

**Comment by zxdavb** [comment]
@jarrah31 I haven't had a chance to work this one out, but I can tell you that there is now a way to get high-precision temperatures from DHW.  Will need an updated client library (which is to be release shortly).

**Comment by jarrah31** [comment]
thanks, happy to wait.

**Comment by zxdavb** [comment]
@jarrah31 I have discovered why the sensor isn't updating, even though the current temperature is changing in the internal state: in the Wiki:
https://github.com/zxdavb/evohome/wiki/DHW-Tips-(incl.-current_temperature)

> NB: the following does not work, see: https://github.com/home-assistant/home-assistant/issues/22197

I am trying to come up with a work-around.

**Comment by zxdavb** [comment]
See: https://github.com/zxdavb/evohome/wiki/DHW-and-Current-Temperature

**Comment by jarrah31** [comment]
superb, thanks! I'll try it out this evening.
