### ISSUE TITLE
How to install next to other custom components?

### ISSUE THREAD

**Issue by WoLpH** [zxdavb/evohome#34]
I think it's partially due to this change: https://github.com/zxdavb/evohome/issues/29
But I can't think of a "good" way to install this component next to other custom components.

The installation instructions (https://github.com/zxdavb/evohome/tree/master/evohome_cc#installation-instructions) say that I need to run:
```
git clone https://github.com/zxdavb/evohome.git custom_components
```

Which would work great if I had no other custom components since it effectively replaces the directory. If all of the files would be in the top-level directory I could do this instead:
```
mkdir -p custom_components
cd custom_components
git clone https://github.com/zxdavb/evohome.git evohome_cc
```

For the time being I can work around it with a symlink or something, but the current method is definitely inconvenient.

**Comment by zxdavb** [comment]
Sorry, the installation instructions are out of date.  Try [this](https://github.com/zxdavb/evohome/wiki/Installation-Instructions).

**Comment by WoLpH** [comment]
Awesome! Thanks for the quick fix. I absolutely love this component, it definitely should be included in the core at some point

**Comment by zxdavb** [comment]
HA made it too hard for me to update the official version of this component, so I needed a break from that - I will try again later, but will work on the custom component version for a while.

**Comment by WoLpH** [comment]
Yeah... it can be a pain. It depends who's reviewing it. I've had a few attempts that got merged within a few hours and I've had an attempt that took weeks.

**Comment by zxdavb** [comment]
If it was only that...

**Comment by WoLpH** [comment]
Not to worry, if the install method is easy enough (especially with the component updater) it will work great for most people.

Once everything has been running stable for a while it shouldn't be too hard to get it merged in. But it will definitely take effort... I guess it's a lesson they've learned from the past because there are quite a few components in HASS that are written pretty horrible.

**Comment by zxdavb** [comment]
> If it was only that...

It can't get merged in - there was a fiasco with `water_heaters` - they don't have a `current_temperature` (for a start).

**Comment by WoLpH** [comment]
Yeah... that would require a substantial change internally... I wouldn't completely lose hope just yet but don't waste any time on it :)
