### ISSUE TITLE
Error upon start [0.90.0B0]

### ISSUE THREAD

**Issue by Swiftnesses** [zxdavb/evohome#36]
```
Error during setup of component evohome_cc
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/evohome_cc/__init__.py", line 195, in setup
    evo_data['params'] = dict(hass_config[DOMAIN])
KeyError: 'evohome'
```

**Comment by Swiftnesses** [comment]
Any ideas?

**Comment by zxdavb** [comment]
Some. **evohome_cc** is no more - I switched it back to **evohome**, which makes me suspect you're using an old version of the component?

It now supports `custom_updater` too. so do you wanna have a go at: https://github.com/zxdavb/evohome/wiki/Installation 

Let mw know whoe you get on - happy to help if you're still stuck after that.

**Comment by Swiftnesses** [comment]
Well, that explains it, I just needed to update my config file ;-)

**Comment by zxdavb** [comment]
Close?
