### ISSUE TITLE
Custom Updater Version not same as Current Version

### ISSUE THREAD

**Issue by Beertje135** [zxdavb/evohome#46]
Custom Updater files refers to 1.5.0 and init.py refers to 1.4.9.

**Comment by Beertje135** [comment]
Update must have crossed the issue request. Updated all to 1.5.1

**Comment by zxdavb** [comment]
Known problem, fix has just been pushed to master, v1.5.1 - there is no difference except for the correction to the version numbers.

I will close this, but let me know if that doesn't work for you...

**Comment by zxdavb** [comment]
> Update must have crossed the issue request. Updated all to 1.5.1

No, I had the fix for a while, just forgot - you prompted me to push it.
