### ISSUE TITLE
cannot start client.py: TypeError

### ISSUE THREAD

**Issue by nl0pvm** [zxdavb/evohome#48]
```
python3 client.py monitor /dev/ttyUSB0 -o packet.log
```
gives
```
Traceback (most recent call last):
  File "client.py", line 21, in <module>
    from ramses_rf import Gateway, GracefulExit, is_valid_dev_id
  File "/home/pv/ramses_rf/ramses_rf/__init__.py", line 16, in <module>
    from .const import __dev_mode__
  File "/home/pv/ramses_rf/ramses_rf/const.py", line 9, in <module>
    from .protocol.const import (  # noqa: F401
  File "/home/pv/ramses_rf/ramses_rf/protocol/__init__.py", line 9, in <module>
    from .address import Address, is_valid_dev_id
  File "/home/pv/ramses_rf/ramses_rf/protocol/address.py", line 24, in <module>
    DEVICE_LOOKUP |= {"NUL": "63", "---": "--"}
```

```
pip list | grep -E '(serial|click)'
click                  8.1.3               
pyserial               3.4                 
pyserial-asyncio       0.6
```

```
python3 -V
Python 3.8.10
```

**Comment by zxdavb** [comment]
Hi, 

You have not provided a full traceback.

You have not said which version of the repo you are using. This product is in active development - please use a tagged release, or the master branch.

The latest version only support Python >=3.9.x

**Comment by nl0pvm** [comment]
I am sorry for not providing you with these quite essential details. And thank you very much for answering so fast! You even made it to give me (a good) answer as I am running the latest and greatest version on and older version of python. So that's indeed the root cause. Have you got any directions on what version is still python 3.8 compatible?

BREAK

I went on the python 3.9 path that seemed the easiest... but hey... I now ran into this issue:

```
python3.9 client.py monitor /dev/ttyACM0 

Traceback (most recent call last):
  File "/home/pveerman/ramses_rf/client.py", line 32, in <module>
    from ramses_rf.schemas import (
ImportError: cannot import name 'SCH_PACKET_LOG' from 'ramses_rf.schemas' (/home/pv/ramses_rf/ramses_rf/schemas.py)```

**Comment by nl0pvm** [comment]
Because of a new commit the error is away and it works now.

**Comment by nl0pvm** [comment]
Because of a new commit the error is away and it works now.
