### ISSUE TITLE
Update to work with HACS

### ISSUE THREAD

**Issue by quentinsf** [zxdavb/evohome#48]
Hi David - 

There are a couple of changes needed to make the component work with HACS (the rather nice replacement for custom_updater).  Nothing very significant, but it does involve a change in directory layout, so I didn't want just to do this as a PR.  (Happy to send you one if wanted, though.)

The details are here:  https://custom-components.github.io/hacs/developer/integration/

I think the main thing is that the key files need to be moved into a directory called custom_components/evohome.

Thanks again,
Quentin

**Comment by zxdavb** [comment]
@quentinsf 

HA is about to go live with [climate-1.0](https://github.com/home-assistant/home-assistant/pull/23899) - this is very exciting! Essentially, it will make the `custom_component` version obsolete:
 - DHW support is ready to go, just need to submit the PR
 - OAuth access tokens are now cached (no more API limit exceeded) - can poll every 60 secs (in testing, I poll every 10 secs!)
 - high-res temps are missing, but can be added back before Winter
 - The inheritance of operating mode between the controller and each zone is now exposed via teh new HA UI
 - many other tweaks (e.g. reset mode)

**climate-1.0** will be in beta come 3-4 days.

**Comment by quentinsf** [comment]
Ah, splendid!  I'll wait for that!

**Comment by Swiftnesses** [comment]
This stopped working for me, I see climate 1.0 hit beta, what changes do we need to make?

**Comment by zxdavb** [comment]
The new evohome is now in beta - docs are [here](
https://rc.home-assistant.io/components/evohome), you need to install HA from v0.96b2 onwards, instructions [here](https://www.home-assistant.io/docs/installation/updating/).

Please report any issues [here](https://github.com/home-assistant/home-assistant/issues).

**Comment by quentinsf** [comment]
I've now got the new climate world running, and it seems to be working fine!  Many thanks for all your efforts on this, and it's great to get it into the core!  Congrats!

Q

**Comment by zxdavb** [comment]
So much work! My wife has started making comments!

**Comment by quentinsf** [comment]
You can tell her that many people appreciate your labours!
