### ISSUE TITLE
Configuration invalid: Invalid config for [evohome]: required key not provided 

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/evohome#6]
Configuration validation via the web UI (`Configuration` -> `General` -> `CHECK CONFIG`) fails with error message: 
`Invalid config for [evohome]: required key not provided @ data['platform']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/evohome/`

Nonetheless, the component behaves as expected.

(the developer would appreciate any help with this issue)

**Comment by matthewcky2k** [comment]
im thinking maybe this is because its a climate component and its not configured the same as Climate > platform? rather than just a Platform?

**Comment by zxdavb** [comment]
Thanks for your input.

I have just switched to developing this as a regular component (i.e. not a custom component, so that I can submit a pull request to HA), and in that case the error has disappeared.

Shortly I will provide instructions for those who are interested on how to shoe horn this into their H A installations as a regular component.
