### ISSUE TITLE
device type 30 not known to have signature: 0002FF1E02FFFFFFFF

### ISSUE THREAD

**Issue by thigger** [zxdavb/evohome#80]
`2023-04-20 13:30:38.501 WARNING (MainThread) [ramses_rf.protocol.parsers]  I --- 30:071715 --:------ 30:071715 10E0 038 000002FF1E02FFFFFFFF100107DF110A07DE496E7465726E6574204761746577617900000000 < Support the development of ramses_rf by reporting this packet, with the make/model of device: RFG:071715 (device type 30 not known to have signature: 0002FF1E02FFFFFFFF)
`

This is a Honeywell Evohome RFG100 - from an older Evohome setup

**Comment by zxdavb** [comment]
Thanks - I will do the necessaries.
