### ISSUE TITLE
Problems with Ramses_rf after migrating to Elga Ace

### ISSUE THREAD

**Issue by JBSDM** [zxdavb/evohome#81]
Hello,

I have a HGI80 installed in combination with Home Assistant. This worked like a charm when my Evohome was connected to my Remeha Calenta. But since a month we have a hybrid heat pump and the Evohome is migrated towards this device. After that i do not get good data from the HGI80. Do you have any idea how that is possible?

If you need any information from me i would love to give it to fix my issue... i don't like the Cloud connection to Evohome.

Best Regards,

JBSDM

**Comment by zxdavb** [comment]
Hello, as a first step, you would have to supply me with packet logs, please. minimum 24h.

**Comment by JBSDM** [comment]
I will make a packet log. What is de best way to share it with you?

**Comment by JBSDM** [comment]
I added all again and the problem is fixed now:)
